/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as ProtectedDashboardRouteRouteImport } from './routes/_protected/dashboard/route'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedDashboardRouteRoute = ProtectedDashboardRouteRouteImport.update({
  id: '/_protected/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedDashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof ProtectedDashboardRouteRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/': typeof PublicIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRouteRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/about' | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/' | '/dashboard'
  id:
    | '__root__'
    | '/_public'
    | '/_protected/dashboard'
    | '/_public/about'
    | '/_public/'
    | '/_protected/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ProtectedDashboardRouteRoute: typeof ProtectedDashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedDashboardRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface ProtectedDashboardRouteRouteChildren {
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
}

const ProtectedDashboardRouteRouteChildren: ProtectedDashboardRouteRouteChildren =
  {
    ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  }

const ProtectedDashboardRouteRouteWithChildren =
  ProtectedDashboardRouteRoute._addFileChildren(
    ProtectedDashboardRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ProtectedDashboardRouteRoute: ProtectedDashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
